### ISSUE TITLE
Inverse Taylor expansion

### ISSUE THREAD

**Issue by rospoly** [soarlab/FPTaylor#30]
Hi Alexey,

this might be just a question rather than an issue. I'm debugging FPTaylor (to double-check the results from my probabilistic tool).

In the case of the inverse operator, the coefficient for the first-order error terms is -1/f(x)*f(x)

Thus, should be the line 422 (link below)
`let mk_v1 v0 e = mk_neg (mk_div const_1 (mk_mul v0 v0)) in`
rather than
`let mk_v1 v0 e = mk_neg (mk_div e (mk_mul v0 v0)) in`

Thank you and sorry again for this very debugging question.

https://github.com/soarlab/FPTaylor/blob/efbbc83970fe3c9f4cb33fafbbe1050dd18749cd/taylor_form.ml#L422

**Comment by monadius** [comment]
Hi Rocco,

The function `mk_v1` computes the product of the first-order Taylor coefficient and the corresponding error term. You are right that the coefficient of the inverse operation is `-1/(f(x) * f(x))`. But it is multiplied by the existing error term `e`: `-1/(f(x) * f(x)) * e`. That's why the final expression is `-(e / (f(x) * f(x))`.

The full expression looks like this: `inv(f + e) = f + -1/(f * f) * e + O(e^2) = f - e / (f * f) + O(e^2)`.

Feel free to open issues to ask questions.
